spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
